sudo: false
language: scala

scala:
  - 2.11.12
  - 2.12.11
  - 2.13.2
jdk:
  - openjdk8
env:
  # marker environment variable to make the build matrix more readable in the UI
  - JOB=test

script:
  - >
    sbt coverage
    "++$TRAVIS_SCALA_VERSION scalafmtCheckAll"
    "++$TRAVIS_SCALA_VERSION test"
    "++$TRAVIS_SCALA_VERSION doc"
    "++$TRAVIS_SCALA_VERSION publishLocal"

  # Compile example project
  - (cd example; sbt ++$TRAVIS_SCALA_VERSION test)

  # Run tut and check if there are no changes in docs.
  #
  # We're running tut only in Scala 2.12 because it fails the compile step in
  # the presence of comments in 2.13: https://github.com/tpolecat/tut/issues/246
  - if [[ $TRAVIS_SCALA_VERSION =~ ^2\.12.* ]]; then
      sbt "++$TRAVIS_SCALA_VERSION tut";
      git diff --exit-code;
      fi

# Coverage is being uploaded by GitHub Actions
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION "++$TRAVIS_SCALA_VERSION coverageReport" coverageAggregate coveralls

jobs:
  include:
    - env: JOB=build_website
      scala: 2.12.10
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev # required to avoid SSL errors
      before_install:
        - export PATH=${PATH}:./vendor/bundle
        - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      install:
        - rvm use 2.6 --install --fuzzy
        - gem install sass jekyll:4.0.0 html-proofer:3.9.3
      script:
        - sbt makeMicrosite
        - htmlproofer
            --allow-hash-href
            --url-swap "https\://github\.com/pureconfig/pureconfig/tree/master:file\://$(pwd)"
            --url-ignore "/search.maven.org/"
            docs/target/site
      after_success: ignore

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
